### ISSUE TITLE
 stack build error

### ISSUE THREAD

**Issue by marineLZ** [biocom-uib/vpf-tools#13]
$ stack build
HttpExceptionRequest Request {
  host                 = "github.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/bielr/fused-effects/archive/8bd165aa7b1c8ee61a94fe6c2f42d756c2c8ab8d.tar.gz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout

**Comment by bielr** [comment]
Can you confirm that that URL is accessible from this computer? (github.com/bielr/fused-effects/archive/8bd165aa7b1c8ee61a94fe6c2f42d756c2c8ab8d.tar.gz)

**Comment by marineLZ** [comment]
Thanks for your promt reply, bielr. I can access this file from my computer（windows），but cannot in my server（centos 8）. What can i do if i download this file from my windows, and then upload to my server?

**Comment by bielr** [comment]
That download is part of the build process. The build system (stack) automatically downloads and installs dependencies, so a working internet connection is required to build vpf-class.

**Comment by marineLZ** [comment]
Ok, thanks for your advice. I will try vpn later.

**Comment by marineLZ** [comment]
Dear bielr, thanks for your beautiful app. I have successful installed it.

**Comment by bielr** [comment]
Much appreciated!
