### ISSUE TITLE
index.yaml

### ISSUE THREAD

**Issue by bishav6708** [biocom-uib/vpf-tools#14]
Where can I find index.yaml file? Is it a database or a file we should create based on our data?

**Comment by bielr** [comment]
Hi @bishav6708,

Sorry for the delay. `index.yaml` is a configuration file that points to all the required input files (excluding your data). You can write your own or use the one included in the provided tarball ([from the README](bioinfo.uib.es/~recerca/VPF-Class/vpf-class-data.tar.gz)).
