### ISSUE TITLE
vpf-class thresholds

### ISSUE THREAD

**Issue by wangyaxiang008** [biocom-uib/vpf-tools#15]
hi, 
  Thank you very much for providing such a useful virus classification and host prediction software.
  My question is how to choose the thresholds for membership_ratio and confidence_score.For example, a contig will have multiple results in family.tsv, how do I filter this table.
  Hope to get your reply.
wyx

**Comment by bielr** [comment]
Hi @wangyaxiang008,

In general, the way to do it is to do a brief data analysis of the output. Things to consider:
- Each input sequence gets a single confidence_score and multiple classifications (with a membership_ratio each)
- membership_ratio should be at least 0.1-0.2 -- below that threshold there is usually a lot of noise

Then, I'd recommend plotting the confidence_score of your output to find out how good your predictions were in general and drop anything you would consider that falls too low. This pretty much depends on how much you value precision compared to number of results: the more VPFs had quality results against your sequence the highest its confidence_score will be.

For membership_ratio, there is usually a threshold where you obtain at most 1-3 results for each input sequence. To find this threshold for your data is just a matter of testing a few thresholds and choosing which one works for you. Again, as long as your threshold is above 0.1 or 0.2 it should be reasonable and then it depends on how much you want to consider multiple possibilities compared to "whatever has the highest score" (even if there is a almost a tie).

**Comment by wangyaxiang008** [comment]
@bielr 
Thanks for your reply.
  First ,I plotted a confidence_score distribution of my data，How can I choose the threshold for confidence_score from the graph.
![image](https://user-images.githubusercontent.com/54664252/155341581-6be567e8-23e7-41e3-9200-5a023f1833d7.png)

Another question is how do I choose the threshold for membership_ratio. Is a threshold chosen so that each sequence has only one classification?
Thanks.

**Comment by wangyaxiang008** [comment]
Here is a graph of membership_ratio and confidence_score
![image](https://user-images.githubusercontent.com/54664252/155342254-91f8e39c-2708-469b-895d-a61862969126.png)

**Comment by bielr** [comment]
According to your plots, there seem to be all types of confidence_score's, so the quantity/quality ratio remains at your discretion (this happens with any tool that doesn't set arbitrary defaults).

To find a good threshold for confidence_score and a starting point for membership_ratio, I'd recommend filling the following table and plotting it as a heatmap:
confidence_score_threshold | membership_ratio_threshold | number of remaining distinct sequences

Regarding membership_ratio, the idea is to increase the threshold progressively from 0.1 or 0.2 until only a reasonable amount of classifications remain (1-3 per sequence) and not many sequences are lost. Increasing it to around 0.5 should almost guarantee a single result per sequence at the cost of dropping any sequence with reasonable doubts (i.e. 0.3 Family1, 0.4 Family2, 0.3 Family3). A way to measure this is to plot the distribution of the highest membership_ratio per sequence and see if it is reasonable to set a high membership_ratio threshold or there are many of those almost-ties.

Of course there is always the easy solution: drop all but the classification with highest membership_ratio of each sequence and choose the highest confidence_score that provides enough results for you.
