### ISSUE TITLE
hmms

### ISSUE THREAD

**Issue by YH12314** [biocom-uib/vpf-tools#16]
Hello, thank you for your tools.

The following problems occurred when running the code. I wonder what caused them?

Hope to get your reply.
![1](https://user-images.githubusercontent.com/101385532/163664434-abfafb48-4538-43af-9c3f-531e9f04eef3.png)

**Comment by bielr** [comment]
Hi,

Looks like the hmms file might be corrupted, your HMMER version could be too old or it can't find final_list.hmms. You could try the following:
- Re-download final_list.hmms and verify that it was downloaded successfully.
- Check that final_list.hmms is present in that path.
- Update HMMER

**Comment by mengyan-zhou** [comment]
Hi，

because the link doesn't open, I can't get the final_list.hmms. Are there other methods I can get this file?
If possible, could you send this file to my email (1489230035@qq.com)? 
thanks in advance!

**Comment by bielr** [comment]
Hi,

Thank you for the heads up! We didn't notice that the link was broken, you can find a copy [here](http://bioinfo.uib.es/~recerca/VPF-Class/vpf-class-data/final_list.hmms) (it's about 3GB). Hope that helps

**Comment by mengyan-zhou** [comment]
Hi,
Thanks for your reply! I found the copy of "final_list.hmms ". but could you send me a download link?
Thank you in advance!

**Comment by bielr** [comment]
Sorry for the late reply, the link is both in the previous comment and in the README
