### ISSUE TITLE
openFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by in3ska** [biocom-uib/vpf-tools#19]
Hello, 

I am having difficulties running vpf-tools. I used your VPF classification from https://bioinfo.uib.es/~recerca/VPF-Class/. Below is the answer I get:

```
user@user-iMac vpf-tools % stack exec -- vpf-class --data-index data/index.yaml -i contigs.fna -o TEST
searching hits
processsed 295 sequences        
processing hits
predicting memberships
loading VPF classifications
vpf-class: data/./vpf_classification/2019_VPF_BaltTax_REclassification.txt: openFile: does not exist (No such file or directory)
```

I noticed that the files in data/uvig_scores and data/vpf_classification are .tsv and not .txt. So I changed them and also the files in data/vpf_classification contain a new extension "_new.tsv". I then changed these to ".txt". Now I received the following response:

```
user@user-iMac vpf-tools % stack exec -- vpf-class --data-index data/index.yaml -i contigs.fna -o TEST
searching hits
processsed 295 sequences
processing hits
predicting memberships
loading VPF classifications
vpf-class: data/./vpf_classification/2019_VPF_PhylHost_REclassification.txt: openFile: does not exist (No such file or directory)
```

I checked via the link you provided to see if this file exists, but it does not. 

I look forward to your reply.

**Comment by bielr** [comment]
Hi,

You are absolutely correct. Some file names were terribly outdated in the index.yaml, they should be fixed now.

Thank you for the heads up!

**Comment by in3ska** [comment]
Hi,

thank you very much! Everything is working now.
