### ISSUE TITLE
what is the index.yaml?

### ISSUE THREAD

**Issue by jiaojiaoguan** [biocom-uib/vpf-tools#21]
Hi,
`stack exec -- vpf-class --data-index ../data/index.yaml -i ../data/test.fna -o test-classified`

I want to know how I can get the `index.yaml.` 
Can I use the `index.yaml` from your provided data link `https://bioinfo.uib.es/~recerca/VPF-Class/vpf-class-data.tar.gz?`

**Comment by bielr** [comment]
Hi,

Yes, you can simply use the provided one.

**Comment by jiaojiaoguan** [comment]
thank you

**Comment by SergeyBaikal** [comment]
Is the link working for sure?
