### ISSUE TITLE
Different data file in "vpf-class/" directory

### ISSUE THREAD

**Issue by jiaojiaoguan** [biocom-uib/vpf-tools#22]
Hi,
I know that there are different data in `vpf-class/` (you provided), like this:
![image](https://user-images.githubusercontent.com/43172888/174420228-3e0bd336-d538-42b2-94aa-0362c6c57107.png)

If I want to use my data to do classification in genus level, should I use `2019_VPF_GenTax_REclassification_new.tsv` file?

I think that when the program is running, the default file is `2019_VPF_BaltTax_REclassification_new.tsv`. So how can I chage the file?

Thank you very much for your reply.

**Comment by bielr** [comment]
Hi,

All files are used independently, and they are all enabled by default. VPF-Class spends most of the time running prodigal/hmmsearch, so disbling the ones you don't need shouldn't have a massive impact on performance. To check which ones are used for what output file, you may look at index.yaml, there you can simply remove the entries (whole) that you don't want.
