### ISSUE TITLE
cannot parse value `data/index.yaml'

### ISSUE THREAD

**Issue by marineLZ** [biocom-uib/vpf-tools#26]
stack exec -- vpf-class --data-index ./data/index.yaml --hmmer-prefix /usr/local/bin -i ./test/cat_virome.fna  -o  cat_virome_classified _result
option --data-index: cannot parse value `data/index.yaml'

The index.yaml  are in ./data directory but cannot parse value `data/index.yaml

**Comment by bielr** [comment]
You are absolutely correct. That's a regression from a Docker-related feature.

Thanks for reporting.
