### ISSUE TITLE
[RFC] dockerfile for install vpf-tools

### ISSUE THREAD

**Issue by KimYannn** [biocom-uib/vpf-tools#3]

**Comment by bielr** [comment]
Hi @KimBioInfoStudio,

We did not consider providing images or dockerfiles at all, but it sounds good to me, specially for external dependencies like Prodigal or HMMER. Unfortunately we are busy right now, but I'll leave this issue open until someone submits a PR or we have time to provide one.

Thanks for the input,
Biel

**Comment by bielr** [comment]
@KimBioInfoStudio 

You may want to check out the docker branch, there you can find information on a docker image we are trying out now.
