### ISSUE TITLE
ICTV updated viral taxonomy

### ISSUE THREAD

**Issue by MengzhiJ** [biocom-uib/vpf-tools#31]
Hi,
Thanks a lot for providing such a useful viral classification software. I noted that the latest ICTV  classification abolished the order Caudovirales. However, the VPF-class can only analyze viral taxonomy according to previous ICTV classification. How should I solve this problem?
Hope to get your reply.

**Comment by bielr** [comment]
Hi @MengzhiJ,

Thank you for the compliments! The updated ICTV classification is planned for the future version of VPF-Class together with more data from IMG/VR3 (see #11). Unfortunately there is no estimate for the new release date yet.

**Comment by MengzhiJ** [comment]
> Hi @MengzhiJ,
> 
> Thank you for the compliments! The updated ICTV classification is planned for the future version of VPF-Class together with more data from IMG/VR3 (see #11). Unfortunately there is no estimate for the new release date yet.

Thank you for your reply. Hope to see the new version of VPF-Class soon!
