### ISSUE TITLE
Please include a link to the VPFs

### ISSUE THREAD

**Issue by michoug** [biocom-uib/vpf-tools#4]
Hi,
I was looking for quite a long time for the VPFs ("Full data" and "UViG Score samples") and I finally found them in the link to the supplementary data of your paper (http://bioinfo.uib.es/~recerca/VPF-Class/) but it should probably be indicated somewhere on this page
Best regards
Greg

**Comment by bielr** [comment]
Hi @michoug,

Apologies for the delay, notifications were disabled by default. Indeed there was a link in the README, but it had empty text and was not displayed. This is fixed now, thanks for the feedback!

Regards,
Biel
