### ISSUE TITLE
HMMSearchNotFound 

### ISSUE THREAD

**Issue by sly-cell** [biocom-uib/vpf-tools#7]
Hi,

I have installed the vpf-class, but I had some problem when loading HMMER. It could not find HMMSearch, so I added `--hmmer-prefix` according to the usage( `--hmmer-prefix   HMMER     Prefix to the HMMER installation (e.g. HMMER/bin/hmmsearch must exist)`), and I got this error:

`hmmsearch error: HMMSearchNotFound {hmmerConfig = HMMERConfig {hmmerPrefix = Just (Tagged "/lustre/software/hmmer/3.2.1/gcc/4.8.5/")}}`

In fact, my hmmsearch in` /lustre/software/hmmer/3.2.1/gcc/4.8.5/bin/hmmsearch` is executable. I also tried other possible paths such as `/lustre/software/hmmer/` or `/lustre/software/hmmer/3.2.1/gcc/4.8.5/bin/hmmsearch`, but they all failed. I wonder if I have missed something?

Best regards

**Comment by bielr** [comment]
Hi,

I haven't been able to reproduce this. Some ideas that came to my mind:

- Does the path `/lustre/software/hmmer/3.2.1/gcc/4.8.5/bin/hmmsearch` contain any broken symlinks?
- Does the command `/lustre/software/hmmer/3.2.1/gcc/4.8.5/bin/hmmsearch -h` work as expected? (no linker errors, etc)
- Are you using any special configuration (like a cluster) or is this a single machine?

Hope this helps

**Comment by sly-cell** [comment]
Hi, @bielr thank you for your reply. I have checked the path, it is a direct link, and the `/lustre/software/hmmer/3.2.1/gcc/4.8.5/bin/hmmsearch -h` also works well. 

But it is worth noting that codes are run through` sbatch` to Slurm rather than on a single machine. Normally I will use` module load HAMMER/3.2.1-gcc-4.8.5` to load HMMER (of course did not work in this case). Maybe something is different on a cluster? 

Here is my complete code:

`singularity exec vpf-tools.sif stack exec -- vpf-class --data-index ../data/data-index.yaml -i ncl95_1kb.fasta -o test_classified --workers 28 --prodigal /lustre/software/prodigal/2.6.3/gcc/4.8.5/bin/prodigal --hmmer-prefix /lustre/software/hmmer/3.2.1/gcc/4.8.5/`

(Here I used singularity for I once met some problem when installing vpf-class. It now works well except a `WARNING: seccomp requested but not enabled, seccomp library is missing or too old.` Hope more information would help solve this  problem.)

**Comment by bielr** [comment]
Hi, 

Unfortunately I do not have access to any cluster (or Slurm) currently, so these are just guesses.

- Make sure that `hmmsearch` is avaiable from the singularity container, no Slurm involved.
- Is `hmmsearch` automatically available in your PATH when `module load`ing it? If so, `vpf-class` should be able to find it without further configuration.

After some research, I think it must be related to [this](https://sylabs.io/guides/3.7/user-guide/quick_start.html#working-with-files). If `/lustre` is not your home directory, then it may not be accessible from your container by default.

**Comment by sly-cell** [comment]
Sorry for the delay. 
Installing HMM and Prodigal into the container did solve this problem. The reference helped me a lot. 
Thank you!
