### ISSUE TITLE
Stack doesn't build

### ISSUE THREAD

**Issue by Ale-Rossi** [biocom-uib/vpf-tools#8]
I installed stack as suggested, using launching curl -sSL https://get.haskellstack.org/ | sudo sh
Then I downloaded the github repository, following the commands in the README.
stack build, though, does not work and prints this output:
`x86_64-conda-linux-gnu-cc' failed in phase `Linker'. (Exit code: 1)

--  While building simple Setup.hs (scroll up to its section to see the error) using:
      /home/bioinfo/.stack/programs/x86_64-linux/ghc-8.10.2/bin/ghc-8.10.2 -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-3.2.0.0 /home/bioinfo/.stack/setup-exe-src/setup-mPHDZzAJ.hs /home/bioinfo/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/bioinfo/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_3.2.0.0_ghc-8.10.2
    Process exited with code: ExitFailure 1

**Comment by bielr** [comment]
Could you provide more details about your setup and the full logs?

My guess is that there are some inconsistencies between the environment where stack was installed and the environment where you are compiling vpf-class.

**Comment by Ale-Rossi** [comment]
I'm running Ubuntu server edition 18.04.5

I've removed stack, reinstalled it and tried to launch stack build again, all from the /home/bioinfo/programs/vpf-tools directory (which is not found in the PATH).

The output of stack install is the following:
[stack_install_log.txt](https://github.com/biocom-uib/vpf-tools/files/6416202/stack_install_log.txt)

While this is the output of stack build:
[stack_build_log.txt](https://github.com/biocom-uib/vpf-tools/files/6416198/stack_build_log.txt)

The installation and build were attempted in the conda "base" environment, which comprises the following packages:
[conda_base_env.txt](https://github.com/biocom-uib/vpf-tools/files/6416234/conda_base_env.txt)

If you need, this is the output of the _env_ command:
[env_output.txt](https://github.com/biocom-uib/vpf-tools/files/6416247/env_output.txt)

I hope this helps with the debugging

**Comment by bielr** [comment]
I don't know the interactions between stack and conda, but their installer seems to be very confused due to the conda environment. After a quick search, I found that there is a stack package in conda-forge, so I would suggest using that instead of the `curl ... | sh` method for your setup.

**Comment by Ale-Rossi** [comment]
I tried to install stack with conda, but I've come across the same error:

[conda_stack_build.txt](https://github.com/biocom-uib/vpf-tools/files/6453446/conda_stack_build.txt)

**Comment by bielr** [comment]
I can't provide any more input on this issue, sorry. Does it work for you without any Conda stuff?
