### ISSUE TITLE
HMMSearch Error

### ISSUE THREAD

**Issue by KennthShang** [biocom-uib/vpf-tools#9]
Hi, 
When I am running your code, it seems there is an error shown below:
![image](https://user-images.githubusercontent.com/22445402/130718270-912aeaf3-7dc8-4c94-a539-f14b1b419133.png)
I am not sure whether it is caused by myself? Seems something is missing here.

**Comment by KennthShang** [comment]
I also got another problem when installing vpf-tools on our hpc.
![image](https://user-images.githubusercontent.com/22445402/130721966-bf136d71-f60e-4535-9522-06b3f8fe8ac1.png)

Do you have any idea of this?

**Comment by bielr** [comment]
For the first issue, did you download final_list.hmms from IMG/VR as explained in the readme? It looks like either the file is missing our something went wrong with fild permissions.

For the second issue, please read the stack documentation (haskellstack.com) to check that you are not missing any dependencies. The stack tool is not ours, and that error is unrelated to our software.

**Comment by KennthShang** [comment]
Thanks！ But I found another problem when running the code
![image](https://user-images.githubusercontent.com/22445402/131119364-40f89f74-b73e-45e2-b1a4-6424f8ebe6e2.png)
Do you have any idea?

**Comment by bielr** [comment]
Looks like you are missing required data for the classification. Have you downloaded the data files from the supplementary material?

**Comment by KennthShang** [comment]
Yes, like this 
![image](https://user-images.githubusercontent.com/22445402/131132191-f95bebe8-de8f-4578-a1ab-c9c8cd05f4f0.png)

**Comment by KennthShang** [comment]
But in the README file. baltimore.tsv is a file generated by the program right?

**Comment by KennthShang** [comment]
I found out the problem. You use the same name for the required data in the yaml and the predcition file in README

**Comment by bielr** [comment]
There is a baltimore.tsv in the output, but there should be (a different) one in vpf-classification, which is the one to be used to compute the output. Could you verify that all paths in index.yaml are available? (relative to the data directory).

**Comment by KennthShang** [comment]
Yes, it works now. There is a conflict in your README file, so I thought the yaml is to define the output

**Comment by bielr** [comment]
Updated the README to better explain this. Is it OK now?

**Comment by KennthShang** [comment]
I mean, actually, we do not need to write the yaml file ourselves. There is a given one in the supplementary file:
![image](https://user-images.githubusercontent.com/22445402/131161598-62745a63-c86f-40ba-a941-8c4fa27f297b.png)
What we need to do is to change the name from txt into tsv. And this index.yaml is nothing to do with the output file.

But in the README, it states: if the contents of ../data/data-index.yaml are
![image](https://user-images.githubusercontent.com/22445402/131161781-b7202190-2f65-476a-8040-919f94d74b14.png)
Then we will get 
![image](https://user-images.githubusercontent.com/22445402/131161809-a5cb4800-8cbc-4546-96e0-b3cffca6853b.png)

But they do not have any connections. All the path and file name in the yaml file should be related to the downloaded files. Users cannot rename the output files but only the folder ( when using the -o parameter)

Thus, for a users' purpose, you can say, we supply the yaml file, and you can use the given command and the given yaml file to get the result. The classification type is given in the yaml file. You can `#` before the line if you do not need to use it. 

This might be more clear for users.

Best,
Jiayu

**Comment by bielr** [comment]
Thanks for the input!

The output names come directly from this yaml file. Each key (baltimore, host_family, etc) corresponds to an output file. This is, you can rename them to whatever you want, all these classifications are currently independent of their taxonomic meaning as that information is provided by the actual `classificationFiles`.

Following your suggestion, I have removed the contents of `index.yaml` file from the README to avoid confusion and added a troubleshooting section at the end.

**Comment by franztastic** [comment]
> Hi,
> When I am running your code, it seems there is an error shown below:
> ![image](https://user-images.githubusercontent.com/22445402/130718270-912aeaf3-7dc8-4c94-a539-f14b1b419133.png)
> I am not sure whether it is caused by myself? Seems something is missing here.

Hello! How did you manage to solve that?

**Comment by bielr** [comment]
Hi @franztastic 

Looks like you're missing final_list.hmms in the data directory.

**Comment by franztastic** [comment]
Hello, I finally have it running, thank you very much! @bielr

**Comment by franztastic** [comment]
Hola @bielr .
Don't know what happens with hmmer everytime I need to run VPF-Class... 

I have final_list.hmm in the same file, as in the folder /data/ but nonetheless it seems it can't find it. 

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/8795082/133096516-a5750813-9941-4de0-9099-277983c0cac0.png">

I had it working and now I'm trying to re-execute it I have the same problem again... Is there anything else I need to do? 

Thank you very much

**Comment by bielr** [comment]
Hola @franztastic,

If you read the error carefully, it says that it can't find hmmsearch (the tool itself). I'm guessing that it's not in your path, so you should specify the prefix of your hmmer installation using the `--hmmer-prefix` flag.
